# Generated by Django 4.0.4 on 2022-12-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_quest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quest_type',
            field=models.CharField(choices=[('Daily Quest', 'Daily'), ('Site Quest', 'Site'), ('Main Quest', 'Main'), ('Story Quest', 'Story')], default='Daily Quest', max_length=20, null=True),
        ),
    ]
